version: '2.2'

volumes:
  cache:
  log:

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
        - /var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=masz
      - MYSQL_USER=mysqldummy
      - MYSQL_PASSWORD=mysqldummy
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - appnetwork

  backend:    
    container_name: backend
    depends_on:
        db:
            condition: service_healthy
    build: backend
    restart: unless-stopped
    networks:
      - appnetwork
    volumes:
      - /filehost

  webinterface:
    build: webinterface
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/app/public
    ports:
    - "5566:80"
    volumes:
      - ./webinterface:/var/www/html
      - ./webinterface/config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - cache:/var/www/html/app/var/cache
      - log:/var/www/html/app/var/log
  
  nginx:    
    container_name: nginx
    depends_on:
        - db
        - backend
    build: nginx
    restart: unless-stopped
    ports:
      - "5565:80"
    networks:
    - appnetwork

networks:
  appnetwork:
    driver: bridge
