version: '2.2'

volumes:
  php_share:
  mysql:
  filehost:

services:
  db:
    container_name: masz_db
    image: mysql:5.7
    volumes:
        - mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - appnetwork

  backend:
    container_name: masz_backend
    depends_on:
        db:
            condition: service_healthy
    build: backend
    restart: unless-stopped
    networks:
      - appnetwork
    volumes:
      - filehost:/filehost

  sf4_apache:
    build: apache
    container_name: masz_sf4_apache
    volumes:
      - ./apache/config/vhosts:/etc/apache2/sites-enabled
      - php_share:/home/wwwroot/sf4
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - appnetwork

  php:
    build: webinterface
    container_name: masz_sf4_php
    restart: unless-stopped
    volumes:
      - php_share:/home/wwwroot/sf4
    networks:
      - appnetwork

  nginx:
    container_name: masz_nginx
    restart: unless-stopped
    depends_on:
        - db
        - backend
        - sf4_apache
    build: nginx
    restart: unless-stopped
    ports:
      - "5565:80"
    networks:
    - appnetwork

  discordbot:
    build: discordbot
    container_name: masz_discordbot
    restart: unless-stopped
    networks:
      - appnetwork
    environment:
      - BOT_PREFIX=${BOT_PREFIX}

networks:
  appnetwork:
    driver: bridge
