version: '2.2'
services:
  db:
    network_mode: "bridge"
    image: mysql:5.7
    volumes:
        - /var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: masz
        MYSQL_USER: mysqldummy
        MYSQL_PASSWORD: mysqldummy
        MYSQL_PORT: 3306
    ports:
      - "33061:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  backend:
    network_mode: "host"
    depends_on:
        db:
            condition: service_healthy
    build: backend
    restart: on-failure
    ports:
      - "5565:5565"

   
