contact_links:
  - name: MASZ Community Discord
    url: https://discord.gg/5zjpzw6h3S
    about: Visit our discord guild for quick help.
  - name: Security & Bug reports
    url: https://znpn.xyz/0prxi
    about: Please report security vulnerabilities directly to me via mail.
