name: Backend/masz
on: [pull_request]

jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building docker
      run: |
        cd backend
        docker build -t discord-masz .