name: DockerCompose
on: [pull_request]

jobs:
  BuildTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: |
        ./bootstrap_init.sh
        docker-compose build
        docker-compose up -d
  SmokeTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: |
        ./bootstrap_init.sh
        docker-compose build
        docker-compose up -d
    - name: Test
      run: |
        cd tests
        sleep 5s
        python3 -m pip install -r requirements.txt
        python3 -m pytest -v --junitxml=results/test-results.xml .

