name: DockerCompose
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: |
        docker-compose --env-file ./tests/.docker.env up -d
  SmokeTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: |
        docker-compose --env-file ./tests/.docker.env up -d
    - name: Test
      run: |
        cd tests
        sleep 60s
        python3 -m pip install -r requirements.txt
        python3 -m pytest -v --junitxml=results/test-results.xml .

